GET https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}

###

DELETE https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}

###

# devstral-small-2-24B
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./devstral-small-2-24B-instruct-2512.json

###

# gpt-oss-120b-Q8_0
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./gpt-oss-120b-Q8_0.json

###

# gemma-3-12b-it-qat
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./gemma-3-12b-it-qat-Q8_0.json

###

# gemma-3-27b-it-qat
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./gemma-3-27b-it-qat-Q8_0.json

###

# granite-4.0-h-small
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./granite-4.0-h-small.json

###

# phi-4-reasoning-plus
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./phi-4-reasoning-plus.json

###

# glm-4.6v-flash
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./glm-4.6v-flash.json

###

# qwen3-vl-30b-a3b-instruct
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./qwen3-vl-30b-a3b-instruct.json

###

# qwen3-vl-30b-a3b-thinking
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./qwen3-vl-30b-a3b-thinking.json

###

# nemotron-3-nano-30b-a3b
PUT https://{{hostname}}:{{port}}/admin/llamacpp
Authorization: Bearer {{apikey}}
Content-Type: application/json

< ./nemotron-3-nano-30b-a3b.json
